let cont=document.querySelector("#container");
let para=document.createElement("p");
let ht=document.createElement("h3");
para.textContent="Hey, I'm Red";
ht.textContent="I'm a blue H3";
para.style.color="red";
ht.style.color="blue";
cont.appendChild(para);
cont.appendChild(ht);
let secdev=document.createElement("div");
secdev.style.border="thick solid black";
secdev.style.backgroundColor="pink";
let sech=document.createElement("h1");
sech.textContent="I'm in a div";
let secp=document.createElement("p");
secp.textContent="ME TOO";
secdev.appendChild(sech);
secdev.appendChild(secp);
cont.appendChild(secdev);
